### ISSUE TITLE
Can't work on OS X with python version 3.4

### ISSUE THREAD

**Issue by pandarison** [thomasjball/PyExZ3#10]
Hi. I can't get it work on Py3.4 with my Mac. 
I installed pyexz3 following the 'MacOS specific'.
Running this "python3 pyexz3.py test/loop.py" and I got:

Traceback (most recent call last):
  File "pyexz3.py", line 10, in <module>
    from symbolic.explore import ExplorationEngine
  File "/Users/_/Develop/PyExZ3/symbolic/explore.py", line 7, in <module>
    from .z3_wrap import Z3Wrapper
  File "/Users/_/Develop/PyExZ3/symbolic/z3_wrap.py", line 7, in <module>
    from z3 import *
ImportError: bad magic number in 'z3': b'\x03\xf3\r\n'

I have tried to run it under Py2.7, but got another error.
I would appreciate any help. Thanks.

**Comment by as900** [comment]
Hi @pandarison , I have got the same question with Py2.7, and I haven't found the newest.py file from http://z3.codeplex.com/releases/view/101918 given by you. Can you please tell me where can I find the newest.py file please. Thank you so much for your help.
