### ISSUE TITLE
make a cvc test directory

### ISSUE THREAD

**Issue by thomasjball** [thomasjball/PyExZ3#15]
Let's keep a separate directory for tests that require CVC.

-- Tom

**Comment by GroundPound** [comment]
I've created a subdirectory of `test` for CVC-specific test cases. `run_test.py` will ignore this directory and the tests it contains so the behavior of `python run_tests.py test` is unaffected. To perform the CVC-specific tests: `python run_tests.py --cvc test/cvc`. 

Eventually I'd like to get these test cases to work with Z3 as well. To do so requires reorganizing the Z3 wrapper and encoding the string constraints.

I'm closing this issue for now but definitely open to an alternative organization of the tests cases.
