### ISSUE TITLE
Vagrant Box not found

### ISSUE THREAD

**Issue by zhenyu-zhou** [thomasjball/PyExZ3#22]
Hi I'm looking for a tool for python SE. I'm using Mac and all stuffs in `MacOS specific` section seems to work well. However, the command `vagrant up` throws such an error:

==> linux: Box 'chef/debian-7.4' could not be found. Attempting to find and install...
    linux: Box Provider: virtualbox
    linux: Box Version: >= 0
The box 'chef/debian-7.4' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/chef/debian-7.4"]
Error: The requested URL returned error: 404 Not Found

It seems that the Vagrant Box is somehow missing. I'm not familiar with Vagrant and can anybody tell me how to get access to that box?

Thanks!

**Comment by GroundPound** [comment]
Vagrant isn't necessary to run on Mac OS. But if you want to use Vagrant, you can change the box to be an official Debian one: https://atlas.hashicorp.com/debian/boxes/wheezy64

**Comment by zhenyu-zhou** [comment]
Thank you! So is Vagrant optional for Linux as well? If so, I may choose to not use it because I indeed have no idea what it is...

**Comment by GroundPound** [comment]
Vagrant is a easy way to setup project-specific development environments in virtual machines and containers. You don't have to use it on any platform.
